### ISSUE TITLE
Error: Hot module replacement only works with RTCWebSocketExecutor

### ISSUE THREAD

**Issue by luisbebop** [bartgryszko/react-native-example#1]
Hi. Nice app.

I'm trying to run it following your instructions without success. I'm getting the error bellow:

<img width="377" alt="screen shot 2015-10-07 at 3 27 27 am" src="https://cloud.githubusercontent.com/assets/31821/10326425/a25825b6-6ca3-11e5-902a-4d679e10b405.png">

Any idea?

**Comment by bartgryszko** [comment]
Hi, thanks. You need to have Chrome dev tools open while running the app. Follow instructions on the screen - click Cmd + D while having iOS simulator opened. The developer menu will popup. Select Debug in Chrome from this menu.

**Comment by kako0507** [comment]
I got the same error. Is "index.ios.js" missing?

**Comment by bartgryszko** [comment]
@kako0507 index.ios.js will be generated by webpack on the fly.

You have to make sure you have a) packager running (`npm start`) in the console before you've run project in XCode. b) Chrome opened (it's needed for Hot Module Replacement) c) You have enabled `Debug in Chrome` by clicking CMD+D and enabling it. 

If you can't make Dev menu to pop-up while clicking CMD+D because of a red screen, click Dismiss first.

Let me know if that helps.

**Comment by kako0507** [comment]
It works. Thanks!!  :+1:

**Comment by luisbebop** [comment]
Thanks!

**Comment by thedgbrt** [comment]
Any hint on making this work on an actual device? I changed the config files by replacing localhost with my ip address but doesn't seem to solve the issue.

**Comment by bartgryszko** [comment]
@dagobertrenouf I didn't try run it in dev mode with webpack, but I ran it in "production" as a bundle by `npm run bundle`, and uncommenting this: https://github.com/bgryszko/react-native-example/blob/master/ios/AroundMe/AppDelegate.m#L46

**Comment by thedgbrt** [comment]
@bgryszko thank you for your help! I did and here is what I get. On the device I only see a white empty screen.

```
Oct 20 19:34:18  AroundMe[1103] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Oct 20 19:34:18  AroundMe[1103] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2015-10-20 19:34:18.425 [warn][tid:main][RCTDevMenu.m:211] RCTSourceCode module scriptURL has not been set
```

**Comment by bartgryszko** [comment]
@dagobertrenouf you are trying to run it "as is"? If so double check if you have uncommented the line I was talking about, and ran bundle command. When it finished, you should be able to run it (without weback running – native packager should open and the app should open on your device). Does app install on your device at all ?

**Comment by thedgbrt** [comment]
@bgryszko I realize I hadn't accurately followed the instructions, instead of uncommenting https://github.com/bgryszko/react-native-example/blob/master/ios/AroundMe/AppDelegate.m#L46 I commented out this one https://github.com/bgryszko/react-native-example/blob/master/ios/AroundMe/AppDelegate.m#L34

![Facepalm](https://i.imgur.com/iWKad22.jpg)

This works like a charm indeed.

Thank you.
